from tkinter import *
def name():
 name=name_box.get()
 name_list.insert(END,name)
 name_box.focus()
def clear():
 name_list.delete(0,END)
 name_box.focus()
w=Tk()

w.configure(background="red")
w.title("Names List")
w.geometry("600x400")
label1=Label(text="Enter Your Name: ")
label1.place(x=20,y=30,width=200,height=25)
name_box=Entry(text=0)
name_box.place(x=250,y=30,width=200,height=25)
name_box.focus()
button1=Button(text="Add to list",command=name)
button1.place(x=250,y=70,width=200,height=25)
name_list=Listbox()
name_list.place(x=20,y=70,width=200,height=100)
button2=Button(text="Clear List",command=clear)
button2.place(x=250,y=110,width=200,height=25)
w.mainloop()
